config/routes.rb
TwitterQuiz::Application.routes.draw do
  devise_for :users
  devise_for :user do
    match '/user/sign_in/twitter' => Devise::Twitter::Rack::Signin
    match '/user/connect/twitter' => Devise::Twitter::Rack::Connect
  end

  match 'questions/ask/:id' => 'questions#ask'
  match 'submitted_answers/update' => 'submitted_answers#update'
  match 'submitted_answers/mark_correct/:id' => 'submitted_answers#mark_correct'
  match 'quizzes/standings/:id' => 'quizzes#standings'

  resources :questions
  resources :quizzes

  match '/twitter_em_server', :to => Tweet
  root :to => 'welcome#index'
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  load_and_authorize_resource

  def standings
    @quiz = Quiz.find(params[:id])
  end

  # GET /quizzes
  # GET /quizzes.xml
  def index
    set_tab :quizzes
    @quizzes = Quiz.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @quizzes }
    end
  end

  # GET /quizzes/1
  # GET /quizzes/1.xml
  def show
    @quiz = Quiz.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @quiz }
    end
  end

  # GET /quizzes/new
  # GET /quizzes/new.xml
  def new
    set_tab :new_quiz
    @quiz = Quiz.new(:user_id => current_user.id)
    2.times { @quiz.questions.build }

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @quiz }
    end
  end

  # GET /quizzes/1/edit
  def edit
    @quiz = Quiz.find(params[:id])
  end

  # POST /quizzes
  # POST /quizzes.xml
  def create
    @quiz = Quiz.new(params[:quiz])

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to(@quiz, :notice => 'Quiz was successfully created.') }
        format.xml  { render :xml => @quiz, :status => :created, :location => @quiz }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @quiz.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /quizzes/1
  # PUT /quizzes/1.xml
  def update
    @quiz = Quiz.find(params[:id])

    respond_to do |format|
      if @quiz.update_attributes(params[:quiz])
        format.html { redirect_to(@quiz, :notice => 'Quiz was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @quiz.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.xml
  def destroy
    @quiz = Quiz.find(params[:id])
    @quiz.destroy

    respond_to do |format|
      format.html { redirect_to(quizzes_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
  <div class="group">
    <%= f.label :name, t("activerecord.attributes.quiz.name", :default => "Name"), :class => :label %>
    <%= f.text_field :name, :class => 'text_field' %>
    <span class="description">Ex: My First Quiz</span>
  </div>

    <%= f.hidden_field :user_id %>

  <% f.fields_for :questions do |builder| %>  
  <div class="group">  
    <%= builder.label :body, "Question", :class => :label %><br />  
    <%= builder.text_area :body, :rows => 3 %>  
  </div>

    <div class="group">
        <%= builder.label :answer, "Answer", :class => :label %></br>
        <%= builder.text_area :answer, :rows => 2 %>
    </div>  

    <div class="group">
        <%= builder.label :points, "Points", :class => :label %>
        <%= builder.select :points, [1,2,3,4,5] %>
    </div>
    <hr />
  <% end %>

<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
    <%= link_to t("web-app-theme.cancel", :default => "Cancel"), quizzes_path, :class => "text_button_padding link_button" %>
</div>

app/views/quizzes/_navigation.html.erb
<!--
<ul class="wat-cf">
  <li class="first active"><%= link_to "Home", root_url %></li>
  <li><%= link_to "New Quiz", new_quiz_path %></li>
  <li><%= link_to "My Quizzes", quizzes_path %></li>
</ul>
-->


<ul class="wat-cf">
<% tabs_tag(:builder => MenuTabBuilder, :open_tabs => {:class => "wat-cf" }) do |tab| %>
    <%= tab.home "Home", root_url %>
    <%= tab.new_quiz "New Quiz", new_quiz_path %>
    <%= tab.quizzes "My Quizzes", quizzes_path %>
  <% end %>
<ul class="wat-cf">

app/views/quizzes/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/quizzes/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", quizzes_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_quiz_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_quiz_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Quiz</h2>
    <div class="inner">
      <%= form_for @quiz, :url => quiz_path(@quiz), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/quizzes/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <%= render :partial => 'quizzes/navigation' %>
  </div> 
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Quizzes</h2>
    <div class="inner">
      <table class="table">
        <tr>
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.quiz.name", :default => t("activerecord.labels.name", :default => "Name")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @quizzes.each do |quiz| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= quiz.id %>
          </td>
                    <td>
            <%= link_to quiz.name, quiz_path(quiz) %>
          </td>
                    <td>
            <%= quiz.created_at.to_s(:pretty) %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", quiz_path(quiz) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_quiz_path(quiz) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", quiz_path(quiz), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/quizzes/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <%= render :partial => 'quizzes/navigation' %>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Quiz</h2>
    <div class="inner">
      <%= form_for @quiz, :url => quizzes_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/quizzes/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", quizzes_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_quiz_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", quiz_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><h2><%= @quiz.name %></h2></b>
        </p>
                <p>
                    <a href="/quizzes/standings/<%= @quiz.id %>">view standings</a>
                </p>    

                <% @quiz.questions.each do |question| %>
                    <h3>Q: <%= question.body %> <i><%= question.points %> point(s)</i></h3>
                    <h3>A: <%= question.answer %></h3>
                    <% if question.asked? %>

                        <span>
                        
                        <%= link_to "#{question.submitted_answers.length} answer(s)", "/questions/ask/#{question.id}" %>
                        
                        <% if question.correct_submitted_answer.nil? %>
                            <a href="/questions/ask/<%= question.id %>">
                                pick the correct answer
                            </a>
                        <% end %>
                        </span>

                    <% else %>
                        <b><%= link_to "Ask!", "/questions/ask/#{question.id}" %></b>
                    <% end %>
                    <br />
                    <br />
                <% end %>    
                
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_quiz_path(@quiz), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), quiz_path(@quiz), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/quizzes/standings.html.erb
<div class="block">
    <div class="content">
        <div class="innner">
            <h2>Standings for <i><%= @quiz.name %></i></h2>
            
            <table class="table">
                <tr>
                    <th>Rank</th>
                    <th>Score</th>
                    <th>User</th>
                </tr>
            
                <% @quiz.scoreboard_entries.ranked.each_with_index do |scoreboard_entry, i| %>
                    <tr>
                        <td><%= i+1 %></td>
                        <td><%= scoreboard_entry.score %></td>
                        <td><%= scoreboard_entry.answerer.username %></td>
                    </tr>
                <% end %>

            </table>

        </div>
    </div>
</div>